[project]
name = "exercise-mobile-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google>=3.0.0",
    "google-api-python-client>=2.176.0",
    "gspread>=6.2.1",
    "pandas>=2.3.1",
    "streamlit>=1.47.0",
    "plotly>=5.17.0",
    "pytest>=8.4.1",
    "plotly-calplot>=0.1.20",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
