name: Remote docker deploy

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1
  
      - name: Login to Docker hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push image
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          push: true
          tags: jhquilty99/workout-monitor:latest
          
      - name: Deploy container in remote host
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker image pull jhquilty99/workout-monitor:latest
            docker container stop workout
            docker container rm workout
            docker container run -d --name workout -p 8501:8501 jhquilty99/workout-monitor